import type { Metadata } from "next";
import { ActiveToolPageFrame } from "@/components/tools/shared/active-tool-page-frame";
import { PdfToPowerPointTool } from "@/components/tools/pdf-to-powerpoint/pdf-to-powerpoint-tool";
import { buildToolMetadata } from "@/lib/seo";

const toolName = "PDF to PowerPoint Online Free — PDFNimbus";
const toolDescription = "Convert each PDF page into a real PPTX image slide. Free browser-first PDF to PowerPoint workflow.";
const faqItems = [
  { question: "Will text stay editable in PowerPoint?", answer: "No. Each PDF page becomes an image slide. Text will not be editable in PowerPoint." },
  { question: "Are files uploaded to a server?", answer: "For typical use, processing is browser-first and files are not stored on our servers." },
  { question: "Is the output a real .pptx file?", answer: "Yes. The tool downloads a real PowerPoint .pptx file." }
];
const faqJsonLd = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqItems.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) };
const softwareJsonLd = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "PDFNimbus PDF to PowerPoint", description: toolDescription, applicationCategory: "BusinessApplication", url: "https://pdfnimbus.vercel.app/tools/pdf-to-powerpoint", operatingSystem: "Web" };
export const metadata: Metadata = buildToolMetadata({ title: toolName, description: toolDescription, canonicalPath: "/tools/pdf-to-powerpoint" });
export default function Page() { return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([softwareJsonLd, faqJsonLd]) }} /><ActiveToolPageFrame currentToolHref="/tools/pdf-to-powerpoint" title={{ en: "PDF to PowerPoint", es: "PDF a PowerPoint" }} subtitle={{ en: "Turn each PDF page into an image-based PowerPoint slide and download a real PPTX file.", es: "Convierte cada pagina PDF en una diapositiva basada en imagen y descarga un archivo PPTX real." }} howToTitle={{ en: "How PDF to PowerPoint works", es: "Como funciona PDF a PowerPoint" }} howToText={{ en: "Render each PDF page as an image and place it on its own slide inside a downloadable PPTX.", es: "Renderiza cada pagina PDF como imagen y la coloca en su propia diapositiva dentro de un PPTX descargable." }} introParagraphs={[{ en: "This workflow is designed for visual slide conversion rather than editable presentation authoring. It keeps slide appearance close to the original PDF by using full-slide page images.", es: "Este flujo esta pensado para conversion visual de diapositivas y no para edicion textual de presentaciones. Mantiene la apariencia cercana al PDF original usando imagenes de pagina a diapositiva completa." }]} benefitsTitle={{ en: "Why use PDF to PowerPoint", es: "Por que usar PDF a PowerPoint" }} benefitsItems={[{ en: "Real downloadable .pptx output", es: "Salida .pptx real descargable" },{ en: "Each page becomes a slide image", es: "Cada pagina se convierte en imagen de diapositiva" },{ en: "Browser-first conversion for typical use", es: "Conversion browser-first para uso normal" },{ en: "Clear limitation: text is not editable", es: "Limitacion clara: el texto no es editable" }]} relatedToolsTitle={{ en: "Related tools", es: "Herramientas relacionadas" }} relatedTools={[{ href: "/tools/powerpoint-to-pdf", label: { en: "PowerPoint to PDF", es: "PowerPoint a PDF" } },{ href: "/tools/pdf-to-word", label: { en: "PDF to Word", es: "PDF a Word" } },{ href: "/tools/pdf-to-jpg", label: { en: "PDF to JPG", es: "PDF a JPG" } }]} relatedGuidesTitle={{ en: "Learn how to use this tool", es: "Aprende a usar esta herramienta" }} relatedGuides={[{ href: "/guides/pdf-to-powerpoint", label: { en: "How to Use PDF to PowerPoint", es: "Como usar PDF a PowerPoint" } },{ href: "/guides/convert-pdf-to-powerpoint", label: { en: "How to Convert PDF to PowerPoint", es: "Como convertir PDF a PowerPoint" } }]} faqItems={faqItems.map((item) => ({ question: { en: item.question, es: item.question }, answer: { en: item.answer, es: item.answer } }))}><PdfToPowerPointTool /></ActiveToolPageFrame></>); }
