import type { Metadata } from "next";
import { GuidePageTemplate } from "@/app/guides/_components/guide-page-template";
import { buildToolMetadata } from "@/lib/seo";
const title = "How to Use PDF to PowerPoint";
const description = "Learn how PDFNimbus turns each PDF page into an image-based PowerPoint slide.";
const articleJsonLd = { "@context": "https://schema.org", "@type": "Article", headline: title, description, author: { "@type": "Organization", name: "PDFNimbus" } };
const howToJsonLd = { "@context": "https://schema.org", "@type": "HowTo", name: title, description, step: [{ "@type": "HowToStep", text: "Open PDF to PowerPoint in PDFNimbus." },{ "@type": "HowToStep", text: "Upload the source PDF." },{ "@type": "HowToStep", text: "Generate the PPTX slide deck." },{ "@type": "HowToStep", text: "Download the PowerPoint file." }] };
export const metadata: Metadata = buildToolMetadata({ title, description, canonicalPath: "/guides/pdf-to-powerpoint" });
export default function Page() { return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([articleJsonLd, howToJsonLd]) }} /><GuidePageTemplate currentGuideHref="/guides/pdf-to-powerpoint" title={title} intro={["PDF to PowerPoint in PDFNimbus creates a real PPTX by rendering each PDF page as an image slide.","This keeps slide appearance close to the original PDF, but text will not be editable in PowerPoint."]} steps={["Open the PDF to PowerPoint tool.","Upload the PDF you want to turn into slides.","Generate the slide deck.","Download the PPTX file."]} ctaHref="/tools/pdf-to-powerpoint" ctaLabel="Use the PDF to PowerPoint tool" benefits={["Real downloadable PPTX output","Visual page-to-slide workflow","Browser-first conversion for typical use","Clear non-editable text limitation"]} relatedTools={[{ href: "/tools/powerpoint-to-pdf", label: "PowerPoint to PDF" },{ href: "/tools/pdf-to-jpg", label: "PDF to JPG" },{ href: "/tools/pdf-to-word", label: "PDF to Word" }]} relatedGuides={[{ href: "/guides/convert-pdf-to-powerpoint", label: "How to Convert PDF to PowerPoint" },{ href: "/guides/powerpoint-to-pdf", label: "How to Use PowerPoint to PDF" }]} faqItems={[{ question: "Will PowerPoint text be editable?", answer: "No. Each PDF page becomes an image slide." },{ question: "Is the output a real PPTX?", answer: "Yes, the tool downloads a real .pptx file." },{ question: "Why use image slides?", answer: "This keeps slide appearance closer to the source PDF in a browser-first workflow." }]} /></>); }
