import type { Metadata } from "next";
import { ActiveToolPageFrame } from "@/components/tools/shared/active-tool-page-frame";
import { ExcelToPdfTool } from "@/components/tools/excel-to-pdf/excel-to-pdf-tool";
import { buildToolMetadata } from "@/lib/seo";

const toolName = "Excel to PDF Online Free — PDFNimbus";
const toolDescription = "Convert simple spreadsheets and table-style documents to PDF in a browser-first workflow. Best for CSV and lightweight exports.";
const faqItems = [
  { question: "Does this preserve advanced Excel formatting?", answer: "No. Best for simple spreadsheets and table-style documents. Advanced formatting may not be preserved." },
  { question: "Can I upload .xlsx files?", answer: "Basic browser-only support is strongest for CSV-style data. XLSX may need export to CSV first." },
  { question: "Are my files uploaded to a server?", answer: "For typical use, processing is browser-first and files are not stored on our servers." }
];
const faqJsonLd = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqItems.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) };
const softwareJsonLd = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "PDFNimbus Excel to PDF", description: toolDescription, applicationCategory: "BusinessApplication", url: "https://pdfnimbus.vercel.app/tools/excel-to-pdf", operatingSystem: "Web" };
export const metadata: Metadata = buildToolMetadata({ title: toolName, description: toolDescription, canonicalPath: "/tools/excel-to-pdf" });
export default function ExcelToPdfPage() {
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([softwareJsonLd, faqJsonLd]) }} /><ActiveToolPageFrame currentToolHref="/tools/excel-to-pdf" title={{ en: "Excel to PDF", es: "Excel a PDF" }} subtitle={{ en: "Convert simple spreadsheets and CSV-style tables into a clean PDF in your browser.", es: "Convierte hojas simples y tablas estilo CSV en un PDF limpio en tu navegador." }} howToTitle={{ en: "How Excel to PDF works", es: "Como funciona Excel a PDF" }} howToText={{ en: "Upload a CSV-style spreadsheet, generate a simple PDF table layout, and download the result.", es: "Sube una hoja tipo CSV, genera un diseño PDF simple de tabla y descarga el resultado." }} introParagraphs={[{ en: "This browser-first flow is best for simple spreadsheets and table-style documents. It does not promise full preservation of formulas, charts, or complex workbook formatting.", es: "Este flujo browser-first funciona mejor con hojas simples y documentos tipo tabla. No promete preservacion completa de formulas, graficos ni maquetaciones complejas." }]} benefitsTitle={{ en: "Why use Excel to PDF", es: "Por que usar Excel a PDF" }} benefitsItems={[{ en: "Best for simple spreadsheets and plain tables", es: "Ideal para hojas simples y tablas basicas" },{ en: "Quick PDF export for lightweight data", es: "Exportacion rapida a PDF para datos ligeros" },{ en: "Browser-first processing for typical use", es: "Procesamiento browser-first para uso normal" },{ en: "Clear limitations for advanced workbook features", es: "Limitaciones claras para funciones avanzadas" }]} relatedToolsTitle={{ en: "Related tools", es: "Herramientas relacionadas" }} relatedTools={[{ href: "/tools/pdf-to-excel", label: { en: "PDF to Excel", es: "PDF a Excel" } },{ href: "/tools/word-to-pdf", label: { en: "Word to PDF", es: "Word a PDF" } },{ href: "/tools/merge-pdf", label: { en: "Merge PDF", es: "Unir PDF" } }]} relatedGuidesTitle={{ en: "Learn how to use this tool", es: "Aprende a usar esta herramienta" }} relatedGuides={[{ href: "/guides/excel-to-pdf", label: { en: "How to Use Excel to PDF", es: "Como usar Excel a PDF" } },{ href: "/guides/convert-excel-to-pdf", label: { en: "How to Convert Excel to PDF", es: "Como convertir Excel a PDF" } }]} faqItems={faqItems.map((item) => ({ question: { en: item.question, es: item.question }, answer: { en: item.answer, es: item.answer } }))}><ExcelToPdfTool /></ActiveToolPageFrame></>);
}
