import type { Metadata } from "next";
import { ActiveToolPageFrame } from "@/components/tools/shared/active-tool-page-frame";
import { PowerPointToPdfTool } from "@/components/tools/powerpoint-to-pdf/powerpoint-to-pdf-tool";
import { buildToolMetadata } from "@/lib/seo";

const toolName = "PowerPoint to PDF Online Free — PDFNimbus";
const toolDescription = "Convert extractable slide images from PowerPoint to PDF in a browser-first workflow with clear rendering limitations.";
const faqItems = [
  { question: "Will complex layouts render perfectly?", answer: "No. Converts slide images to PDF. Complex layouts may not render perfectly." },
  { question: "What if the presentation has no usable images?", answer: "The tool shows: This presentation has no extractable slide images." },
  { question: "Are files uploaded to a server?", answer: "For typical use, processing is browser-first and files are not stored on our servers." }
];
const faqJsonLd = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqItems.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) };
const softwareJsonLd = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "PDFNimbus PowerPoint to PDF", description: toolDescription, applicationCategory: "BusinessApplication", url: "https://pdfnimbus.vercel.app/tools/powerpoint-to-pdf", operatingSystem: "Web" };
export const metadata: Metadata = buildToolMetadata({ title: toolName, description: toolDescription, canonicalPath: "/tools/powerpoint-to-pdf" });
export default function Page() { return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([softwareJsonLd, faqJsonLd]) }} /><ActiveToolPageFrame currentToolHref="/tools/powerpoint-to-pdf" title={{ en: "PowerPoint to PDF", es: "PowerPoint a PDF" }} subtitle={{ en: "Convert extractable slide images from a PPTX presentation into a simple PDF document.", es: "Convierte imagenes de diapositivas extraibles de una presentacion PPTX en un PDF simple." }} howToTitle={{ en: "How PowerPoint to PDF works", es: "Como funciona PowerPoint a PDF" }} howToText={{ en: "Extract usable slide images from a presentation package and place them into PDF pages.", es: "Extrae imagenes utilizables de una presentacion y las coloca en paginas PDF." }} introParagraphs={[{ en: "This browser-first route is limitation-aware. It works best when the presentation contains extractable slide images or media that can be placed into a PDF page.", es: "Esta ruta browser-first es consciente de sus limitaciones. Funciona mejor cuando la presentacion contiene imagenes o medios extraibles que puedan colocarse en una pagina PDF." }]} benefitsTitle={{ en: "Why use PowerPoint to PDF", es: "Por que usar PowerPoint a PDF" }} benefitsItems={[{ en: "Simple PDF export from extractable slide images", es: "Exportacion PDF simple desde imagenes de diapositivas extraibles" },{ en: "Honest browser-first limitation handling", es: "Gestion honesta de limitaciones browser-first" },{ en: "Clear message when no slide images exist", es: "Mensaje claro cuando no existen imagenes de diapositiva" },{ en: "Useful for lightweight presentation conversion", es: "Util para conversion ligera de presentaciones" }]} relatedToolsTitle={{ en: "Related tools", es: "Herramientas relacionadas" }} relatedTools={[{ href: "/tools/pdf-to-powerpoint", label: { en: "PDF to PowerPoint", es: "PDF a PowerPoint" } },{ href: "/tools/pdf-to-excel", label: { en: "PDF to Excel", es: "PDF a Excel" } },{ href: "/tools/compress-pdf", label: { en: "Compress PDF", es: "Comprimir PDF" } }]} relatedGuidesTitle={{ en: "Learn how to use this tool", es: "Aprende a usar esta herramienta" }} relatedGuides={[{ href: "/guides/powerpoint-to-pdf", label: { en: "How to Use PowerPoint to PDF", es: "Como usar PowerPoint a PDF" } },{ href: "/guides/convert-powerpoint-to-pdf", label: { en: "How to Convert PowerPoint to PDF", es: "Como convertir PowerPoint a PDF" } }]} faqItems={faqItems.map((item) => ({ question: { en: item.question, es: item.question }, answer: { en: item.answer, es: item.answer } }))}><PowerPointToPdfTool /></ActiveToolPageFrame></>); }
