import type { Metadata } from "next";
import { GuidePageTemplate } from "@/app/guides/_components/guide-page-template";
import { buildToolMetadata } from "@/lib/seo";
const title = "How to Convert PDF to PowerPoint";
const description = "Convert PDF pages into a PowerPoint slide deck with the browser-first PDFNimbus workflow.";
const articleJsonLd = { "@context": "https://schema.org", "@type": "Article", headline: title, description, author: { "@type": "Organization", name: "PDFNimbus" } };
const howToJsonLd = { "@context": "https://schema.org", "@type": "HowTo", name: title, description, step: [{ "@type": "HowToStep", text: "Open PDF to PowerPoint in PDFNimbus." },{ "@type": "HowToStep", text: "Upload the PDF file." },{ "@type": "HowToStep", text: "Create the PPTX slide deck." },{ "@type": "HowToStep", text: "Download and open the file in PowerPoint." }] };
export const metadata: Metadata = buildToolMetadata({ title, description, canonicalPath: "/guides/convert-pdf-to-powerpoint" });
export default function Page() { return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([articleJsonLd, howToJsonLd]) }} /><GuidePageTemplate currentGuideHref="/guides/convert-pdf-to-powerpoint" title={title} intro={["Converting PDF to PowerPoint is useful when you need a slide deck version of a report, brochure, or presentation-style PDF.","PDFNimbus uses a page-to-image-slide approach instead of text reflow, so the result is visual rather than editable." ]} steps={["Open the PDF to PowerPoint tool.","Upload your PDF.","Generate the PowerPoint file.","Download and present the PPTX slides." ]} ctaHref="/tools/pdf-to-powerpoint" ctaLabel="Convert PDF to PowerPoint" benefits={["Keeps page appearance visually consistent","Fast browser-first conversion path","Good for slide-style playback","Honest limitation on editability"]} relatedTools={[{ href: "/tools/powerpoint-to-pdf", label: "PowerPoint to PDF" },{ href: "/tools/pdf-to-jpg", label: "PDF to JPG" },{ href: "/tools/pdf-to-excel", label: "PDF to Excel" }]} relatedGuides={[{ href: "/guides/pdf-to-powerpoint", label: "How to Use PDF to PowerPoint" },{ href: "/guides/convert-powerpoint-to-pdf", label: "How to Convert PowerPoint to PDF" }]} faqItems={[{ question: "Does it preserve the PDF visually?", answer: "It aims to preserve the visual appearance by using page images on slides." },{ question: "Can I edit the text after conversion?", answer: "No, text is not editable because each page becomes an image slide." },{ question: "Is this useful for presentations?", answer: "Yes, especially when you want a quick slide-based version of a PDF." }]} /></>); }
