import type { Metadata } from "next";
import { GuidePageTemplate } from "@/app/guides/_components/guide-page-template";
import { buildToolMetadata } from "@/lib/seo";
const title = "How to Convert PowerPoint to PDF";
const description = "Convert extractable slide images from PowerPoint to PDF with the browser-first PDFNimbus workflow.";
const articleJsonLd = { "@context": "https://schema.org", "@type": "Article", headline: title, description, author: { "@type": "Organization", name: "PDFNimbus" } };
const howToJsonLd = { "@context": "https://schema.org", "@type": "HowTo", name: title, description, step: [{ "@type": "HowToStep", text: "Open PowerPoint to PDF in PDFNimbus." },{ "@type": "HowToStep", text: "Upload the PPTX file you want to convert." },{ "@type": "HowToStep", text: "Generate the PDF from available slide images." },{ "@type": "HowToStep", text: "Download the converted PDF." }] };
export const metadata: Metadata = buildToolMetadata({ title, description, canonicalPath: "/guides/convert-powerpoint-to-pdf" });
export default function Page() { return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([articleJsonLd, howToJsonLd]) }} /><GuidePageTemplate currentGuideHref="/guides/convert-powerpoint-to-pdf" title={title} intro={["Converting PowerPoint to PDF is practical when you need a shareable, static version of a presentation.","PDFNimbus handles this browser-first by using extractable slide images where available, with honest limits for complex decks." ]} steps={["Open the PowerPoint to PDF tool.","Upload the presentation file.","Generate the PDF conversion.","Download and review the output." ]} ctaHref="/tools/powerpoint-to-pdf" ctaLabel="Convert PowerPoint to PDF" benefits={["Good for lightweight PDF exports","Simple browser-first workflow","Useful for static sharing","Clear limitation handling"]} relatedTools={[{ href: "/tools/pdf-to-powerpoint", label: "PDF to PowerPoint" },{ href: "/tools/compress-pdf", label: "Compress PDF" },{ href: "/tools/merge-pdf", label: "Merge PDF" }]} relatedGuides={[{ href: "/guides/powerpoint-to-pdf", label: "How to Use PowerPoint to PDF" },{ href: "/guides/convert-pdf-to-powerpoint", label: "How to Convert PDF to PowerPoint" }]} faqItems={[{ question: "Will layouts always match perfectly?", answer: "No. Complex layouts may not render perfectly." },{ question: "Can it fail on some decks?", answer: "Yes. Decks without extractable slide images will show a clear limitation message." },{ question: "Is this better for simple presentations?", answer: "Yes, simple slide-image workflows are the best fit." }]} /></>); }
