import type { Metadata } from "next";
import { GuidePageTemplate } from "@/app/guides/_components/guide-page-template";
import { buildToolMetadata } from "@/lib/seo";
const title = "How to Use PowerPoint to PDF";
const description = "Learn how PDFNimbus converts extractable slide images from PPTX presentations into PDF pages.";
const articleJsonLd = { "@context": "https://schema.org", "@type": "Article", headline: title, description, author: { "@type": "Organization", name: "PDFNimbus" } };
const howToJsonLd = { "@context": "https://schema.org", "@type": "HowTo", name: title, description, step: [{ "@type": "HowToStep", text: "Open PowerPoint to PDF in PDFNimbus." },{ "@type": "HowToStep", text: "Upload the PPTX presentation." },{ "@type": "HowToStep", text: "Extract usable slide images and generate a PDF." },{ "@type": "HowToStep", text: "Download the PDF result." }] };
export const metadata: Metadata = buildToolMetadata({ title, description, canonicalPath: "/guides/powerpoint-to-pdf" });
export default function Page() { return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([articleJsonLd, howToJsonLd]) }} /><GuidePageTemplate currentGuideHref="/guides/powerpoint-to-pdf" title={title} intro={["PowerPoint to PDF in PDFNimbus is a limitation-aware browser workflow focused on extractable slide images inside PPTX files.","It is best for simple presentations where slide media can be turned into PDF pages. Complex layouts may not render perfectly." ]} steps={["Open the PowerPoint to PDF tool.","Upload a PPTX file.","Generate the PDF from extractable slide images.","Download and review the PDF output." ]} ctaHref="/tools/powerpoint-to-pdf" ctaLabel="Use the PowerPoint to PDF tool" benefits={["Useful for lightweight presentation export","Browser-first conversion path","Clear error when no slide images exist","Honest layout-fidelity limits"]} relatedTools={[{ href: "/tools/pdf-to-powerpoint", label: "PDF to PowerPoint" },{ href: "/tools/compress-pdf", label: "Compress PDF" },{ href: "/tools/pdf-to-jpg", label: "PDF to JPG" }]} relatedGuides={[{ href: "/guides/convert-powerpoint-to-pdf", label: "How to Convert PowerPoint to PDF" },{ href: "/guides/pdf-to-powerpoint", label: "How to Use PDF to PowerPoint" }]} faqItems={[{ question: "Will every PPTX convert perfectly?", answer: "No. Complex layouts may not render perfectly in this browser-first workflow." },{ question: "What happens if no usable images exist?", answer: "The tool will show: This presentation has no extractable slide images." },{ question: "Is this for simple slide exports?", answer: "Yes, it is best for lightweight presentation-to-PDF use cases." }]} /></>); }
