import type { Metadata } from "next";
import { GuidePageTemplate } from "@/app/guides/_components/guide-page-template";
import { buildToolMetadata } from "@/lib/seo";
const title = "How to Use PDF to Excel";
const description = "Learn how PDFNimbus exports table-like PDF content to CSV for Excel and Google Sheets.";
const articleJsonLd = { "@context": "https://schema.org", "@type": "Article", headline: title, description, author: { "@type": "Organization", name: "PDFNimbus" } };
const howToJsonLd = { "@context": "https://schema.org", "@type": "HowTo", name: title, description, step: [{ "@type": "HowToStep", text: "Open PDF to Excel in PDFNimbus." },{ "@type": "HowToStep", text: "Upload a PDF with table-like content." },{ "@type": "HowToStep", text: "Run CSV extraction." },{ "@type": "HowToStep", text: "Download the CSV and open it in Excel or Sheets." }] };
export const metadata: Metadata = buildToolMetadata({ title, description, canonicalPath: "/guides/pdf-to-excel" });
export default function Page() { return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([articleJsonLd, howToJsonLd]) }} /><GuidePageTemplate currentGuideHref="/guides/pdf-to-excel" title={title} intro={["PDF to Excel in PDFNimbus focuses on practical CSV export for table-like PDFs.","The output downloads as CSV format, compatible with Excel and Google Sheets rather than full .xlsx."]} steps={["Open the PDF to Excel tool.","Upload a PDF with extractable table-like text.","Run the extraction process.","Download the CSV and review the rows in Excel or Sheets."]} ctaHref="/tools/pdf-to-excel" ctaLabel="Use the PDF to Excel tool" benefits={["CSV output compatible with Excel","Good for simple table-like PDFs","Browser-first extraction flow","Clear limitations for complex layouts"]} relatedTools={[{ href: "/tools/excel-to-pdf", label: "Excel to PDF" },{ href: "/tools/pdf-to-word", label: "PDF to Word" },{ href: "/tools/compress-pdf", label: "Compress PDF" }]} relatedGuides={[{ href: "/guides/convert-pdf-to-excel", label: "How to Convert PDF to Excel" },{ href: "/guides/excel-to-pdf", label: "How to Use Excel to PDF" }]} faqItems={[{ question: "Does this create .xlsx files?", answer: "No. It downloads CSV, which opens in Excel and Google Sheets." },{ question: "What PDFs work best?", answer: "Table-like PDFs with extractable text work best." },{ question: "Will complex layouts need cleanup?", answer: "Yes, complex tables may need manual cleanup after export." }]} /></>); }
