import type { Metadata } from "next";
import { GuidePageTemplate } from "@/app/guides/_components/guide-page-template";
import { buildToolMetadata } from "@/lib/seo";
const title = "How to Use Excel to PDF";
const description = "Learn how PDFNimbus converts simple spreadsheets and CSV-style tables into PDF.";
const articleJsonLd = { "@context": "https://schema.org", "@type": "Article", headline: title, description, author: { "@type": "Organization", name: "PDFNimbus" } };
const howToJsonLd = { "@context": "https://schema.org", "@type": "HowTo", name: title, description, step: [{ "@type": "HowToStep", text: "Open Excel to PDF in PDFNimbus." },{ "@type": "HowToStep", text: "Upload a CSV or simple table file." },{ "@type": "HowToStep", text: "Generate a simple PDF table layout." },{ "@type": "HowToStep", text: "Download the PDF export." }] };
export const metadata: Metadata = buildToolMetadata({ title, description, canonicalPath: "/guides/excel-to-pdf" });
export default function Page() { return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([articleJsonLd, howToJsonLd]) }} /><GuidePageTemplate currentGuideHref="/guides/excel-to-pdf" title={title} intro={["Excel to PDF in PDFNimbus is built for simple spreadsheets and table-style documents.","It is best for CSV-style data and lightweight exports, not advanced workbooks with charts, formulas, or complex formatting."]} steps={["Open the Excel to PDF tool.","Upload a CSV, TSV, TXT, or supported simple sheet file.","Generate the PDF table layout.","Download and review the PDF."]} ctaHref="/tools/excel-to-pdf" ctaLabel="Use the Excel to PDF tool" benefits={["Good for simple spreadsheet exports","Fast browser-first PDF creation","Honest handling of advanced-format limitations","Useful for plain table documents"]} relatedTools={[{ href: "/tools/pdf-to-excel", label: "PDF to Excel" },{ href: "/tools/word-to-pdf", label: "Word to PDF" },{ href: "/tools/merge-pdf", label: "Merge PDF" }]} relatedGuides={[{ href: "/guides/convert-excel-to-pdf", label: "How to Convert Excel to PDF" },{ href: "/guides/pdf-to-excel", label: "How to Use PDF to Excel" }]} faqItems={[{ question: "Does this preserve formulas and charts?", answer: "No. It is best for simple spreadsheets and table-style documents." },{ question: "Can I upload XLSX?", answer: "Browser-only support is strongest for CSV-style files; XLSX may need export to CSV first." },{ question: "Is this good for lightweight exports?", answer: "Yes, especially for plain tables and simple sheet data." }]} /></>); }
