import type { Metadata } from "next";
import { ActiveToolPageFrame } from "@/components/tools/shared/active-tool-page-frame";
import { PdfToExcelTool } from "@/components/tools/pdf-to-excel/pdf-to-excel-tool";
import { buildToolMetadata } from "@/lib/seo";

const toolName = "PDF to Excel Online Free — PDFNimbus";
const toolDescription = "Extract table-like text from PDF files and download it as CSV. Free browser-first PDF to Excel-compatible workflow.";
const faqItems = [
  { question: "Does this download .xlsx files?", answer: "No. It downloads as CSV format, compatible with Excel and Google Sheets." },
  { question: "Are my files uploaded to a server?", answer: "For typical use, processing is browser-first and files are not stored on our servers." },
  { question: "Will every PDF convert cleanly?", answer: "No. Complex layouts and scanned PDFs may need manual cleanup after CSV export." }
];
const faqJsonLd = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqItems.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) };
const softwareJsonLd = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "PDFNimbus PDF to Excel", description: toolDescription, applicationCategory: "BusinessApplication", url: "https://pdfnimbus.vercel.app/tools/pdf-to-excel", operatingSystem: "Web" };
export const metadata: Metadata = buildToolMetadata({ title: toolName, description: toolDescription, canonicalPath: "/tools/pdf-to-excel" });
export default function PdfToExcelPage() {
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([softwareJsonLd, faqJsonLd]) }} /><ActiveToolPageFrame currentToolHref="/tools/pdf-to-excel" title={{ en: "PDF to Excel", es: "PDF a Excel" }} subtitle={{ en: "Extract table-like PDF content and download it as CSV for Excel or Google Sheets.", es: "Extrae contenido tipo tabla de PDF y descargalo como CSV para Excel o Google Sheets." }} howToTitle={{ en: "How PDF to Excel works", es: "Como funciona PDF a Excel" }} howToText={{ en: "Upload a PDF, extract text rows, and download CSV output for spreadsheet editing.", es: "Sube un PDF, extrae filas de texto y descarga salida CSV para editar en hoja de calculo." }} introParagraphs={[{ en: "This browser-first workflow focuses on CSV export rather than full .xlsx generation. It works best for table-like PDFs where text can be extracted cleanly.", es: "Este flujo browser-first se centra en exportacion CSV en lugar de generar .xlsx completo. Funciona mejor con PDFs tipo tabla donde el texto puede extraerse con claridad." }]} benefitsTitle={{ en: "Why use PDF to Excel", es: "Por que usar PDF a Excel" }} benefitsItems={[{ en: "CSV output compatible with Excel and Google Sheets", es: "Salida CSV compatible con Excel y Google Sheets" },{ en: "Useful for table-like PDF data extraction", es: "Util para extraer datos de PDFs tipo tabla" },{ en: "Browser-first processing for typical use", es: "Procesamiento browser-first para uso normal" },{ en: "Honest limitation handling for complex layouts", es: "Limitaciones explicitas para maquetaciones complejas" }]} relatedToolsTitle={{ en: "Related tools", es: "Herramientas relacionadas" }} relatedTools={[{ href: "/tools/excel-to-pdf", label: { en: "Excel to PDF", es: "Excel a PDF" } },{ href: "/tools/pdf-to-word", label: { en: "PDF to Word", es: "PDF a Word" } },{ href: "/tools/compress-pdf", label: { en: "Compress PDF", es: "Comprimir PDF" } }]} relatedGuidesTitle={{ en: "Learn how to use this tool", es: "Aprende a usar esta herramienta" }} relatedGuides={[{ href: "/guides/pdf-to-excel", label: { en: "How to Use PDF to Excel", es: "Como usar PDF a Excel" } },{ href: "/guides/convert-pdf-to-excel", label: { en: "How to Convert PDF to Excel", es: "Como convertir PDF a Excel" } }]} faqItems={faqItems.map((item) => ({ question: { en: item.question, es: item.question }, answer: { en: item.answer, es: item.answer } }))}><PdfToExcelTool /></ActiveToolPageFrame></>);
}
