import type { Metadata } from "next";
import { GuidePageTemplate } from "@/app/guides/_components/guide-page-template";
import { buildToolMetadata } from "@/lib/seo";
const title = "How to Convert Excel to PDF";
const description = "Convert simple spreadsheet content to PDF with the browser-first PDFNimbus Excel to PDF workflow.";
const articleJsonLd = { "@context": "https://schema.org", "@type": "Article", headline: title, description, author: { "@type": "Organization", name: "PDFNimbus" } };
const howToJsonLd = { "@context": "https://schema.org", "@type": "HowTo", name: title, description, step: [{ "@type": "HowToStep", text: "Open Excel to PDF in PDFNimbus." },{ "@type": "HowToStep", text: "Upload a CSV-style spreadsheet." },{ "@type": "HowToStep", text: "Generate a PDF table export." },{ "@type": "HowToStep", text: "Download the resulting PDF." }] };
export const metadata: Metadata = buildToolMetadata({ title, description, canonicalPath: "/guides/convert-excel-to-pdf" });
export default function Page() { return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([articleJsonLd, howToJsonLd]) }} /><GuidePageTemplate currentGuideHref="/guides/convert-excel-to-pdf" title={title} intro={["Converting Excel to PDF is useful when you need a shareable, print-ready output from simple spreadsheet data.","PDFNimbus focuses this workflow on plain tables and lightweight exports rather than advanced workbook fidelity."]} steps={["Open the Excel to PDF tool.","Upload your CSV or simple table file.","Create the PDF layout.","Download the finished PDF."]} ctaHref="/tools/excel-to-pdf" ctaLabel="Convert Excel to PDF" benefits={["Portable PDF output for simple sheets","Good for sharing table data","Browser-first workflow","Clear limitations for advanced formatting"]} relatedTools={[{ href: "/tools/pdf-to-excel", label: "PDF to Excel" },{ href: "/tools/word-to-pdf", label: "Word to PDF" },{ href: "/tools/compress-pdf", label: "Compress PDF" }]} relatedGuides={[{ href: "/guides/excel-to-pdf", label: "How to Use Excel to PDF" },{ href: "/guides/convert-pdf-to-excel", label: "How to Convert PDF to Excel" }]} faqItems={[{ question: "Will complex workbook layouts be preserved?", answer: "No. The workflow is best for simple spreadsheets and table-style documents." },{ question: "Is CSV the safest input format right now?", answer: "Yes, CSV-style input works best in the current browser-only stack." },{ question: "Can I round-trip between PDF and spreadsheet formats?", answer: "Yes, PDF to Excel covers the reverse CSV extraction workflow." }]} /></>); }
