import type { Metadata } from "next";
import { GuidePageTemplate } from "@/app/guides/_components/guide-page-template";
import { buildToolMetadata } from "@/lib/seo";
const title = "How to Convert PDF to Excel";
const description = "Convert PDF table-like content to CSV for Excel with the browser-first PDFNimbus workflow.";
const articleJsonLd = { "@context": "https://schema.org", "@type": "Article", headline: title, description, author: { "@type": "Organization", name: "PDFNimbus" } };
const howToJsonLd = { "@context": "https://schema.org", "@type": "HowTo", name: title, description, step: [{ "@type": "HowToStep", text: "Open PDF to Excel in PDFNimbus." },{ "@type": "HowToStep", text: "Upload your PDF file." },{ "@type": "HowToStep", text: "Extract table-like text to CSV." },{ "@type": "HowToStep", text: "Download and refine the CSV in Excel." }] };
export const metadata: Metadata = buildToolMetadata({ title, description, canonicalPath: "/guides/convert-pdf-to-excel" });
export default function Page() { return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([articleJsonLd, howToJsonLd]) }} /><GuidePageTemplate currentGuideHref="/guides/convert-pdf-to-excel" title={title} intro={["Converting PDF to Excel is most useful when the PDF contains rows and columns that can be extracted as structured text.","PDFNimbus exports CSV instead of full .xlsx, keeping the workflow browser-first and honest about limitations."]} steps={["Open the PDF to Excel tool.","Upload the PDF you want to extract.","Run CSV export.","Download the CSV and review it in Excel."]} ctaHref="/tools/pdf-to-excel" ctaLabel="Convert PDF to Excel" benefits={["Fast CSV extraction path","Excel-compatible output","Browser-first workflow","Clear expectation setting"]} relatedTools={[{ href: "/tools/excel-to-pdf", label: "Excel to PDF" },{ href: "/tools/pdf-to-word", label: "PDF to Word" },{ href: "/tools/merge-pdf", label: "Merge PDF" }]} relatedGuides={[{ href: "/guides/pdf-to-excel", label: "How to Use PDF to Excel" },{ href: "/guides/convert-excel-to-pdf", label: "How to Convert Excel to PDF" }]} faqItems={[{ question: "Is the download CSV or XLSX?", answer: "CSV. It is compatible with Excel and Google Sheets." },{ question: "Can scanned PDFs convert well?", answer: "Scanned/image-only PDFs may not extract cleanly in-browser." },{ question: "Can I edit the results later?", answer: "Yes, CSV output can be opened and edited in spreadsheet apps." }]} /></>); }
